name: Update ASG Launch Template

on:
  push:
    branches:
      - main  # Altere para o branch que você deseja monitorar

jobs:
  update-launch-template:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Create AMI from EC2 instance
      id: create_ami
      run: |
        INSTANCE_ID="i-01201b95ea1bb74f5"  # Substitua pelo seu ID de instância
        AMI_NAME="my-app-image-$(date +%Y%m%d%H%M%S)"
        
        AMI_ID=$(aws ec2 create-image --instance-id $INSTANCE_ID --name "$AMI_NAME" --no-reboot --query 'ImageId' --output text)
        echo "AMI ID: $AMI_ID"
        echo "::set-output name=ami_id::$AMI_ID"

    - name: Wait for AMI to become available
      run: |
        AMI_ID=${{ steps.create_ami.outputs.ami_id }}
        echo "Waiting for AMI $AMI_ID to become available..."
        aws ec2 wait image-available --image-ids $AMI_ID

    - name: Update Launch Template
      id: update_launch_template
      run: |
        LAUNCH_TEMPLATE_NAME="app-launch-template20241012112040308500000002"  # Substitua pelo nome do seu Launch Template
        NEW_LAUNCH_TEMPLATE_VERSION=$(aws ec2 create-launch-template-version --launch-template-name $LAUNCH_TEMPLATE_NAME \
          --source-version 1 --launch-template-data "{\"ImageId\":\"${{ steps.create_ami.outputs.ami_id }}\"}" \
          --query 'LaunchTemplateVersion.VersionNumber' --output text)
        
        echo "New Launch Template Version: $NEW_LAUNCH_TEMPLATE_VERSION"
        echo "::set-output name=new_launch_template_version::$NEW_LAUNCH_TEMPLATE_VERSION"

    - name: Update Auto Scaling Group
      run: |
        ASG_NAME="terraform-20241012112041704200000004"  # Substitua pelo nome do seu ASG
        NEW_LAUNCH_TEMPLATE_NAME="app-launch-template20241012112040308500000002"  # Substitua pelo nome do seu Launch Template
        NEW_LAUNCH_TEMPLATE_VERSION=${{ steps.update_launch_template.outputs.new_launch_template_version }}

        aws autoscaling update-auto-scaling-group --auto-scaling-group-name $ASG_NAME \
          --launch-template "LaunchTemplateName=${NEW_LAUNCH_TEMPLATE_NAME},Version=${NEW_LAUNCH_TEMPLATE_VERSION}"

        echo "Auto Scaling Group $ASG_NAME updated to use Launch Template $NEW_LAUNCH_TEMPLATE_NAME version $NEW_LAUNCH_TEMPLATE_VERSION."

    - name: Restart instances in ASG
      run: |
        ASG_NAME="terraform-20241012112041704200000004"  # Substitua pelo nome do seu ASG
        INSTANCE_IDS=$(aws autoscaling describe-auto-scaling-instances --filters "Name=auto-scaling-group-name,Values=$ASG_NAME" --query 'AutoScalingInstances[*].InstanceId' --output text)
        
        echo "Instances to be restarted: $INSTANCE_IDS"

        for INSTANCE_ID in $INSTANCE_IDS; do
          echo "Restarting instance $INSTANCE_ID"
          aws ec2 reboot-instances --instance-ids $INSTANCE_ID
        done
