name: Update ASG Launch Template

on:
  push:
    branches:
      - main  # Altere para o branch que você deseja monitorar

jobs:
  update-launch-template:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Create AMI from EC2 instance
      id: create_ami
      run: |
        INSTANCE_ID="i-01201b95ea1bb74f5"  # Substitua pelo seu ID de instância
        AMI_NAME="my-app-image-$(date +%Y%m%d%H%M%S)"
        
        AMI_ID=$(aws ec2 create-image --instance-id $INSTANCE_ID --name "$AMI_NAME" --no-reboot --query 'ImageId' --output text)
        echo "AMI ID: $AMI_ID"
        echo "::set-output name=ami_id::$AMI_ID"

    - name: Wait for AMI to become available
      run: |
        AMI_ID=${{ steps.create_ami.outputs.ami_id }}
        echo "Waiting for AMI $AMI_ID to become available..."
        aws ec2 wait image-available --image-ids $AMI_ID

    - name: Update Launch Template
      run: |
        LAUNCH_TEMPLATE_NAME="app-launch-template20241012112040308500000002"  # Substitua pelo nome do seu Launch Template
        aws ec2 create-launch-template-version --launch-template-name $LAUNCH_TEMPLATE_NAME \
          --source-version 1 --launch-template-data "{\"ImageId\":\"${{ steps.create_ami.outputs.ami_id }}\"}"
        
        echo "Launch Template $LAUNCH_TEMPLATE_NAME updated with new AMI."
